#!/bin/bash
#
#
# Array of feed urls
FEEDS=(
    'http://showrss.info/user/163617.rss?magnets=true&namespaces=true&name=null&quality=null&re=no'
  )

#
# HOST
TORRENT_CLIENT_HOST="http://192.168.1.77:9091/transmission/rpc"
